---
title: "My Webpage"
author: "Jeanette Clark"
date: "10/10/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT) #install.packages("DT")
library(leaflet)
```


```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e",
                    method = "libcurl"),
                stringsAsFactors = FALSE)
```


# Calculate Annual Escapment for Salmon Species

Calculate total annual escapement by region, year, and species

```{r, results = "hide"}
species_list <- c("Chinook", "Sockeye", "Chum", "Pink", "Coho")


annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = F) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, SASAP.Region, Species) %>% 
  summarise(total_escapement = sum(DailyCount)) %>% 
  filter(Species %in% species_list)
  #filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho"))
  #filter(Species == "Chinook" | Species == "Sockeye" | Species == "Chum")

head(annual_esc)
```


# Visualize Escapement

Total Escapement by Region and Species

```{r, echo = FALSE}
ggplot(data = annual_esc, mapping = aes(x = Species, y = total_escapement, fill = SASAP.Region)) +
  geom_col()
```

Kodiak Escapement Over Time by Species

```{r, echo = FALSE}
my_theme <- theme_bw() +
  theme(legend.position = "bottom")

ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"),
       mapping = aes(x = Year, y = total_escapement, color = Species)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = "lm") +
  scale_color_brewer(palette = "Dark2") +
  ylab("Escapement (no. fish)") +
  ggtitle("Kodiak Salmon Escapement") +
  my_theme
```

Escapement over time: all regions

```{r, fig.width = 7, fig.height = 12, echo = FALSE}
fig1 <- ggplot(annual_esc, aes(x = Year, y = total_escapement, color = Species)) +
  geom_point() +
  geom_line() +
  facet_wrap(~SASAP.Region, scales = "free_y", ncol = 1) +
  my_theme

fig1

ggsave("figures/escapement.png", fig1, width = 12, height = 7, units = "in")
```


# Map Sampling Locations

Create a table with unique sampling locations, latitudes, and longitudes

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r, echo = FALSE}
datatable(locations)
```

```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~ Longitude, lat = ~ Latitude, popup = ~ Location)
```


```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

